### PR TITLE
Introducing the non-persistent history of requests made. It can be made persistent in next change

### PR DESCRIPTION
**Pull request by agrabhi**

### CODE REVIEW

**Comment by omer-iqbal** [comment]
Hi agrabhi,

Sorry, I was out for a few days due to an illness. Thank you very much for this contribution. I tried it and found it useful.

I have a couple of recommendations if you do not mind:

1) What do you think about moving the History button to a menu item so the UI stays cleaner. An example includes the Query menu that has Create search query, and clear query. You could also assign a shortcut to it if you like.
  i) At some point, I thought we could add a toolbar and put buttons for such features on the toolbar. So if you added it on the menu, it could later be shown on the toolbar too.
  ii) However, if you prefer it to stay on the UI, how about adding the History button to the right of "Execute" button. 

2) It would be great to use the .NET naming guidelines for readability on the variable names etc. For example, private variable names could be storageFileName instead of StorageFileName. Although this seems trivial, but it helps with readability. For one, I had assumed StorageFileName was an internal or public variable until I saw it's declaration.

Having said this, I would like to get this into master so it is available for others too. Do you want to make updates (at least for the History button?) before I complete the pull request? Or do you want me to complete the pull request and we can iterate over it?

Thanks,
Omer

**Comment by omer-iqbal** [comment]
And some future requests for your consideration:
1) A button to clear the history. This can perhaps be on the "RequestHistoryWindow",
2) Also record the response code, e.g. 200 vs 404. This is especially useful for POST, DELETE, UPDATE, etc.

**Comment by agrabhi** [comment]
These features have been added

1. Export response to notepad
2. Delete Cred code added - but its not working, some exception
3. Send bearer token to jwt.io
4. change history.
5. Change Native Auth from Always to Auto

**Comment by agrabhi** [comment]
Regarding naming of private properties, couldnt find a guideline which says they should be in camelCase.

**Pull request merged**
